# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Ansible@0
  inputs:
    ansibleInterface: 'remoteMachine'
    connectionOverSsh: 'SSH > Ansible Control Node'
    playbookSourceRemoteMachine: 'ansibleMachine'
    playbookPathAnsibleMachineOnRemoteMachine: '/home/Michael/ansible-practice/windowsservices.yml'
    inventoriesRemoteMachine: 'noInventory'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
